### ISSUE TITLE
Error: listen EADDRINUSE :::3301 while starting ITAA Community edition on MAC osx

### ISSUE THREAD

**Issue by rh0042** [IBM/itaa-docs#19]
getting an error while starting ITAA on mc osx
Tomcat 8.5.61
openjdk-15.0.1
Mac osx 11.1

Using CATALINA_BASE:   /Users/rh42/Architektur/CAApp/CAAppOffline/tomcat
Using CATALINA_HOME:   /Users/rh42/Architektur/CAApp/CAAppOffline/tomcat
Using CATALINA_TMPDIR: /Users/rh42/Architektur/CAApp/CAAppOffline/tomcat/temp
Using JRE_HOME:        ../jre/Contents/Home
Using CLASSPATH:       /Users/rh42/Architektur/CAApp/CAAppOffline/tomcat/bin/bootstrap.jar:/Users/rh42/Architektur/CAApp/CAAppOffline/tomcat/bin/tomcat-juli.jar
Using CATALINA_OPTS:   
Tomcat started.
{ Error: listen EADDRINUSE :::3301
    at Server.setupListenHandle [as _listen2] (net.js:1360:14)
    at listenInCluster (net.js:1401:12)
    at Server.listen (net.js:1485:7)
    at Function.listen (/snapshot/CA-APP/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/snapshot/CA-APP/offline_server.js:704:5)
    at Module._compile (pkg/prelude/bootstrap.js:1261:22)
    at Object.Module._extensions..js (module.js:662:10)
    at Module.load (module.js:564:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1316:12)
    at startup (bootstrap_node.js:240:16)
    at bootstrap_node.js:661:3
  errno: 'EADDRINUSE',
  code: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 3301 }
Error: listen EADDRINUSE :::3301
    at Server.setupListenHandle [as _listen2] (net.js:1360:14)
    at listenInCluster (net.js:1401:12)
    at Server.listen (net.js:1485:7)
    at Function.listen (/snapshot/CA-APP/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/snapshot/CA-APP/offline_server.js:704:5)
    at Module._compile (pkg/prelude/bootstrap.js:1261:22)
    at Object.Module._extensions..js (module.js:662:10)
    at Module.load (module.js:564:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1316:12)
    at startup (bootstrap_node.js:240:16)
    at bootstrap_node.js:661:3
{ Error: listen EADDRINUSE 0.0.0.0:3300
    at Server.setupListenHandle [as _listen2] (net.js:1360:14)
    at listenInCluster (net.js:1401:12)
    at doListen (net.js:1510:7)
    at _combinedTickCallback (internal/process/next_tick.js:142:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
  errno: 'EADDRINUSE',
  code: 'EADDRINUSE',
  syscall: 'listen',
  address: '0.0.0.0',
  port: 3300 }
Error: listen EADDRINUSE 0.0.0.0:3300
    at Server.setupListenHandle [as _listen2] (net.js:1360:14)
    at listenInCluster (net.js:1401:12)
    at doListen (net.js:1510:7)
    at _combinedTickCallback (internal/process/next_tick.js:142:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
Rolands-MBP:CAAppOffline rh42$ ./run.sh
Using CATALINA_BASE:   /Users/rh42/Architektur/CAApp/CAAppOffline/tomcat
Using CATALINA_HOME:   /Users/rh42/Architektur/CAApp/CAAppOffline/tomcat
Using CATALINA_TMPDIR: /Users/rh42/Architektur/CAApp/CAAppOffline/tomcat/temp
Using JRE_HOME:        ../jre/Contents/Home
Using CLASSPATH:       /Users/rh42/Architektur/CAApp/CAAppOffline/tomcat/bin/bootstrap.jar:/Users/rh42/Architektur/CAApp/CAAppOffline/tomcat/bin/tomcat-juli.jar
Using CATALINA_OPTS:   
Tomcat started.
{ Error: listen EADDRINUSE :::3301
    at Server.setupListenHandle [as _listen2] (net.js:1360:14)
    at listenInCluster (net.js:1401:12)
    at Server.listen (net.js:1485:7)
    at Function.listen (/snapshot/CA-APP/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/snapshot/CA-APP/offline_server.js:704:5)
    at Module._compile (pkg/prelude/bootstrap.js:1261:22)
    at Object.Module._extensions..js (module.js:662:10)
    at Module.load (module.js:564:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1316:12)
    at startup (bootstrap_node.js:240:16)
    at bootstrap_node.js:661:3
  errno: 'EADDRINUSE',
  code: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 3301 }
Error: listen EADDRINUSE :::3301
    at Server.setupListenHandle [as _listen2] (net.js:1360:14)
    at listenInCluster (net.js:1401:12)
    at Server.listen (net.js:1485:7)
    at Function.listen (/snapshot/CA-APP/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/snapshot/CA-APP/offline_server.js:704:5)
    at Module._compile (pkg/prelude/bootstrap.js:1261:22)
    at Object.Module._extensions..js (module.js:662:10)
    at Module.load (module.js:564:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1316:12)
    at startup (bootstrap_node.js:240:16)
    at bootstrap_node.js:661:3
{ Error: listen EADDRINUSE 0.0.0.0:3300
    at Server.setupListenHandle [as _listen2] (net.js:1360:14)
    at listenInCluster (net.js:1401:12)
    at doListen (net.js:1510:7)
    at _combinedTickCallback (internal/process/next_tick.js:142:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
  errno: 'EADDRINUSE',
  code: 'EADDRINUSE',
  syscall: 'listen',
  address: '0.0.0.0',
  port: 3300 }
Error: listen EADDRINUSE 0.0.0.0:3300
    at Server.setupListenHandle [as _listen2] (net.js:1360:14)
    at listenInCluster (net.js:1401:12)
    at doListen (net.js:1510:7)
    at _combinedTickCallback (internal/process/next_tick.js:142:11)
    at process._tickCallback (internal/process/next_tick.js:181:9

**Comment by glcraig** [comment]
JDK 15 is not currently supported.  Please see the install instructions regarding supported versions.
