### ISSUE TITLE
Unable to download ppt, doc file - http://localhost:3300 express deprecated res.send(status): Use res.sendStatus(status) instead ../../../../../../snapshot/CA-APP/offline_server.js:36:36 { Error: connect ECONNREFUSED 127.0.0.1:3302

### ISSUE THREAD

**Issue by kishore0549** [IBM/itaa-docs#27]
Hi,
I have set up the tomcat & a JDK version, run the tool. created a project. updated few details then tried to download the word document given me below error: Please verify and provide details. thanks 
kishore@KISHOREs-MacBook-Pro CAAppOffline % ./install.sh 
Please keep this window open until the installation is completed. If any error appears, please rerun the script.
Input tomcat-8.5 folder path(e.g. ~/Desktop/apache-tomcat-8.5.45), then click Enter: /Users/kishore/Documents/IBM/Architectures/CAAppOffline/apache-tomcat-8.5.78
Input jre folder path(e.g. ~/Desktop/jre1.8.0_131.jre), then click Enter: /Users/kishore/Documents/IBM/Architectures/CAAppOffline/jdk-18.jdk          
Installed the application successfully. You can input "./run.sh" to run the application.
kishore@KISHOREs-MacBook-Pro CAAppOffline % ./run.sh 
Using CATALINA_BASE:   /Users/kishore/Documents/IBM/Architectures/CAAppOffline/apache-tomcat-8.5.78
Using CATALINA_HOME:   /Users/kishore/Documents/IBM/Architectures/CAAppOffline/apache-tomcat-8.5.78
Using CATALINA_TMPDIR: /Users/kishore/Documents/IBM/Architectures/CAAppOffline/apache-tomcat-8.5.78/temp
Using JRE_HOME:        /usr/local/opt/openjdk@8
Using CLASSPATH:       /Users/kishore/Documents/IBM/Architectures/CAAppOffline/apache-tomcat-8.5.78/bin/bootstrap.jar:/Users/kishore/Documents/IBM/Architectures/CAAppOffline/apache-tomcat-8.5.78/bin/tomcat-juli.jar
Using CATALINA_OPTS:   
Tomcat started.
Listening on 0.0.0.0, port 3300
Open the offline App by copying and pasting the link below into the address bar of your web browser.

http://localhost:3300
express deprecated res.send(status): Use res.sendStatus(status) instead ../../../../../../snapshot/CA-APP/offline_server.js:36:36
{ Error: connect ECONNREFUSED 127.0.0.1:3302
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 3302 }
Error: connect ECONNREFUSED 127.0.0.1:3302
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)
{ Error: socket hang up
    at createHangUpError (_http_client.js:342:15)
    at Socket.socketCloseListener (_http_client.js:377:23)
    at emitOne (events.js:121:20)
    at Socket.emit (events.js:211:7)
    at TCP._handle.close [as _onclose] (net.js:561:12) code: 'ECONNRESET' }
Error: socket hang up
    at createHangUpError (_http_client.js:342:15)
    at Socket.socketCloseListener (_http_client.js:377:23)
    at emitOne (events.js:121:20)
    at Socket.emit (events.js:211:7)
    at TCP._handle.close [as _onclose] (net.js:561:12)
{ Error: connect ECONNREFUSED 127.0.0.1:3302
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 3302 }
Error: connect ECONNREFUSED 127.0.0.1:3302
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)
{ Error: socket hang up
    at createHangUpError (_http_client.js:342:15)
    at Socket.socketCloseListener (_http_client.js:377:23)
    at emitOne (events.js:121:20)
    at Socket.emit (events.js:211:7)
    at TCP._handle.close [as _onclose] (net.js:561:12) code: 'ECONNRESET' }
Error: socket hang up
    at createHangUpError (_http_client.js:342:15)
    at Socket.socketCloseListener (_http_client.js:377:23)
    at emitOne (events.js:121:20)
    at Socket.emit (events.js:211:7)
    at TCP._handle.close [as _onclose] (net.js:561:12)

**Comment by glcraig** [comment]
@kishore0549 Can you click on the app information link (in Browser) and let me know which version of the "offline"/Community Edition you are running?

**Comment by glcraig** [comment]
These types of errors result from improper permissions for process to tomcat directories/files.  A couple of work arounds include changing file permissions (tomcat/conf files and tomcat/logs files) or run as root  (sudo ./run.sh).

**Comment by kishore0549** [comment]
Hi @glcraig, 
App Version is : Version V3.2.2
Macos 
I have tried giving 777 to all the files within tomcat & CAAppOffline.
Started the app with sudo & also changed the permissions in all the tomcat folders & files, CAAppOffline. you may find below .

-rwxrwxrwx@  1 kishore  staff         78 Feb 26  2021 run.bat
-rwxrwxrwx@  1 kishore  staff       1386 Feb 26  2021 install.sh
-rwxrwxrwx@  1 kishore  staff       1230 Feb 26  2021 install.ps1
drwxr-xr-x@ 98 kishore  staff       3136 Feb 26  2021 images
drwxr-xr-x@  5 kishore  staff        160 Feb 26  2021 docs
-rwxrwxrwx@  1 kishore  staff       7241 Feb 26  2021 ReadMe.md
-rw-r--r--@  1 kishore  staff          0 Feb 26  2021 LICENSE
-rw-r--r--@  1 kishore  staff          8 Feb 26  2021 CODEOWNERS
-rwxrwxrwx@  1 kishore  staff     119572 Feb 26  2021 ArchitectureModelDocumentTemplate.docx
-rwxr-xr-x@  1 kishore  staff  106149558 Feb 26  2021 ca-offline-macos
-rwxrwxrwx@  1 kishore  staff   93689424 Feb 26  2021 ca-offline-win.exe
-rwxrwxrwx@  1 kishore  staff   43133903 Feb 26  2021 DocGenMicroService.war
-rwxrwxrwx@  1 kishore  staff    9633432 Feb 26  2021 MxgraphBackend.war
drwxrwxrwx@  3 kishore  staff         96 Feb 15 17:39 jdk-18.jdk
drwxr-xr-x@  5 kishore  staff        160 Apr 13 14:25 workspace
-rwxrwxrwx@  1 kishore  staff        158 Apr 13 14:46 run.sh
drwxrwxrwx@ 17 kishore  staff        544 Apr 13 14:48 apache-tomcat-8.5.78
drwxr-xr-x@ 18 kishore  staff        576 Apr 13 17:12 tomcat


Apache Tomcat:
drwxr-xr-x@  3 kishore  staff     96 Mar 31 18:05 temp
drwxr-xr-x@ 31 kishore  staff    992 Mar 31 18:05 lib
drwxrwxrwx@ 27 kishore  staff    864 Mar 31 18:05 bin
-rw-r--r--@  1 kishore  staff  16974 Mar 31 18:05 RUNNING.txt
-rw-r--r--@  1 kishore  staff   7314 Mar 31 18:05 RELEASE-NOTES
-rw-r--r--@  1 kishore  staff   3459 Mar 31 18:05 README.md
-rw-r--r--@  1 kishore  staff   1777 Mar 31 18:05 NOTICE
-rw-r--r--@  1 kishore  staff  58068 Mar 31 18:05 LICENSE
-rw-r--r--@  1 kishore  staff   6375 Mar 31 18:05 CONTRIBUTING.md
-rw-r--r--@  1 kishore  staff  20058 Mar 31 18:05 BUILDING.txt
drwxrwxrwx@ 13 kishore  staff    416 Apr 13 14:48 conf
drwxrwxrwx@  8 kishore  staff    256 Apr 13 14:48 logs
drwxr-xr-x@  8 kishore  staff    256 Apr 13 14:48 webapps
drwxr-xr-x@  4 kishore  staff    128 Apr 13 14:49 work

Still no luck on the error. same error. 

express deprecated res.send(status): Use res.sendStatus(status) instead ../../../../../../snapshot/CA-APP/offline_server.js:36:36
{ Error: connect ECONNREFUSED 127.0.0.1:3302
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 3302 }
