### ISSUE TITLE
Error: ENOENT: no such file or directory when adding an image 

### ISSUE THREAD

**Issue by carlosbittrich** [IBM/itaa-docs#28]
I included a png image to my use case basic flow and now I can't export to ppt. I get error: 
{ Error: ENOENT: no such file or directory, open 'workspace/..//workspace/Wallet/offline-images/file_7f1c68ba1737b577.png'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.openSync (pkg/prelude/bootstrap.js:490:32)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.fs.readFileSync (pkg/prelude/bootstrap.js:686:36)
    at Object.fn (/snapshot/CA-APP/offline_server.js:852:17)
    at Router.handleRequest (/snapshot/CA-APP/node_modules/routes-router/index.js:157:19)
    at emitTwo (events.js:126:13)
    at Server.emit (events.js:214:7)
    at parserOnIncoming (_http_server.js:660:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'workspace/..//workspace/Wallet/offline-images/file_7f1c68ba1737b577.png' }

As you can see from the last sentence, it seems to be an error with concatenating the directoy name. 
Regards.
Carlos

**Comment by carlosbittrich** [comment]
One additional comment, the error doesn't happen when exporting to Microsoft doc file, it only files when exporting to powerpoint.

**Comment by glcraig** [comment]
@carlosbittrich Hope you are well.  We will get support to investigate.  Which version are you currently using?

**Comment by carlosbittrich** [comment]
Hola Gary, how can i get my current version? I see that the directories of my last unzip are dated feb, 21. 
Regards.

**Comment by glcraig** [comment]
![Locate_CE_version](https://user-images.githubusercontent.com/17624057/179301155-2f12f846-f96d-45dd-9469-55252f06c8ac.jpg)

**Comment by carlosbittrich** [comment]
Version V3.2.2. It seems I am a little old :-( . I will update.

**Comment by carlosbittrich** [comment]
Downloaded version 3.9 and problem has been resolved there. Best regards.
